name: workloads
project_id: prj_8yaz7u8kgbr69ezrbrw8aczfb9

cluster_env: cluster-env-dev
cluster_compute: cluster-compute-dev

runtime_env:
  working_dir: .
  upload_path: s3://model-registry-dev-mangukiya-v2/Devmangukiya/jobs

entrypoint: bash deploy/jobs/workloads.sh


max_retries: 0
